version: 2.1
jobs:
  job_one:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: echo 'Hello from circleci'
  job_two:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: node version
          command: node -v
      - run:
          name: angular build
          command: yarn ng --build --prod
workflows:
  version: 2
  bobby_sally:
    jobs:
      - job_one
      - job_two 
 
  
   
 

 