version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: echo 'Hello from circleci'
  sally:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: node version
          command: node -v
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally 
 
  
   
 

 