version: 2.1
jobs:
  bobby:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: 'npm install'
  sally:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run: 'node -v'
workflows:
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally 
 
  
   
 

 